# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('description', models.TextField(default='')),
                ('event_output', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.IntegerField(default=0)),
                ('output', models.BooleanField(default=False)),
                ('type', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('pin_number',),
            },
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('socket_number', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pin')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('execution_time', models.TimeField(default=django.utils.timezone.now)),
                ('execution_days', models.CharField(default='', max_length=20)),
                ('events', models.ManyToManyField(to='api.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pin'),
        ),
    ]
