# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocketWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executionTime', models.TimeField(default=django.utils.timezone.now)),
                ('newStatus', models.BooleanField(default=False)),
                ('frequency', models.TextField(default='')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Socket')),
            ],
        ),
    ]
